name: CI

# 언제 워크플로우를 실행할지
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Go 환경 설정
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # 3) 의존성 설치
      - name: Install dependencies
        run: go mod tidy

      # 4) 유닛 테스트 실행 및 커버리지 수집
      - name: Run tests
        run: |
          go test ./... -v -coverprofile=coverage.out
  benchmark:
    name: Benchmark HTTP Endpoints
    runs-on: ubuntu-latest
    needs: build-and-test
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build server binary
        run: go build -o json-benchmark .

      - name: Start HTTP server
        run: |
          nohup ./json-benchmark &
          sleep 3

      - name: Install wrk
        run: sudo apt-get update && sudo apt-get install -y wrk

      - name: Run HTTP benchmark
        run: bash benchmark/run_http.sh | tee benchmark/results_http.txt

      # ↓ 여기만 v3 → v4 로 바꿔주세요
      - name: Upload benchmark result
        uses: actions/upload-artifact@v4
        with:
          name: http-benchmark-results
          path: benchmark/results_http.txt
